spring.security.oauth2.client.registration.github.client-id=Ov23limqvlzd0cLbCuzx
spring.security.oauth2.client.registration.github.client-secret=2103814b5bc61516c748c0a99e02c8f4405a4a1e
# Request GitHub scopes: profile info and email address
spring.security.oauth2.client.registration.github.scope=read:user,user:email

#below properties for railway database connection for deployement
sspring.application.name=safe-trip-planner

spring.datasource.url=jdbc:mysql://reseau.proxy.rlwy.net:43872/railway
spring.datasource.username=root
spring.datasource.password=crEJCBvESKdJNrGJIKZZzwfrdIIuDamf

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}
